project:
  title: "Jakub Štenc"
  output-dir: ./docs

website:
  navbar:
    logo: "images/pyl.png"  
    left:
      - href: about.qmd
        text: About me
      - href: CV.qmd
        text: CV
      - href: research.qmd
        text: Research
      - href: PEG.qmd
        text: PEG
    right:
      - icon: github
        href: https://github.com/jakubstenc
      - icon: twitter
        href: https://twitter.com/Cotylledon
      - text: "{{< ai google-scholar size=xl >}}"
        href: https://scholar.google.com/citations?user=xxxxx=en
      - icon: orcid 
        text: "{{< ai orcid size=xl >}}"
        href: https://orcid.org/0000-0003-0678-8452
      - href: /cz/
        text: Česky
  page-footer: 
    left: "Copyright 2024, Jakub Štenc" 
    right: 
      - icon: github
        href: https://github.com/jakubstenc
      - icon: twitter 
        href: https://twitter.com/ 

lang: en

format:
  html:
    theme: sandstone
    toc: true
