---
title: ""
format:
  pdf:
    toc: false
    number-sections: false
    colorlinks: true
    pdf-engine: pdflatex
---

<div>

# Jakub Štenc

## Current position

-   Employee at the Department of Zoology, Faculty of Science, Charles University with project [GACR POSTDOC INDIVIDUAL FELLOWSHIP OUTGOING](https://gacr.cz/pif-out-2026/) awarded in 2024, focusing on pollinator sharing among plant species.

-   Currently hosted as postdoc at [CREAF](https://www.creaf.cat/en) within the GEIP group of [Jordi Bosch](https://orcid.org/0000-0002-8088-9457).

## Contact

-   jakubstenc at gmail.com

-   +420 774 553 734

## Education

-   2015-2018 - Bachelor's degree in biology, Faculty of Science, Charles university. Thesis: Pollination efficiency as a function of plant spatial aggregation and pollinator functional traits. Graduated.

-   2018-2020 - Master's degree in Botany, specialization Geobotany, Faculty of Science, Charles university. Thesis: Changes in pollinator behaviour under different plant spatial aggregation. Graduated with distinction.

-   2020-2024- Ph.D. in Botany, Faculty of Science, Charles university. Thesis: Factors influencing pollen carryover effectiveness. Graduated cuma sum laude.

## Work

-   2019 - 2021 - Part-time employment as a technician at the Department of Botany, mainly managing the lab and reconstruction related activity, 0.1 FTE

-   2023 - 2025 - Employment on the INTER-ACTION-LUAUS23 project led by Petr Sklenář focusing on Pollination in tropical mountains, 0.5 FTE

-   2024 - 2025 - Employment on [Institute of Botany of the Czech Academy of](https://www.ibot.cas.cz/en/) [Sciences](https://www.ibot.cas.cz/en/)

-   2025 - 2028 - Employee at the Department of Zoology, Faculty of Science, Charles University with project [GACR POSTDOC INDIVIDUAL FELLOWSHIP OUTGOING](https://gacr.cz/pif-out-2026/) awarded in 2024, focusing on pollinator sharing among plant species

## Grant support

-   2018-2021 - Co-investigator of grant project from Grant Agency of Charles University: Plant population dynamics under anther smut epidemy and influence of pollinators on the rate of disease spread (1193619)

-   2019-2022 - Main investigator of grant project from Grant Agency of Charles University: Flower traits as drivers of pollinator visitation behaviour (842120)

-   2021-2023 - Main investigator of grant project from Grant Agency of Charles University STAR: Do the plant pollen presentation schedules fit pollinator diurnal activity? A test of the Pollen Presentation Theory (0016935)

-   2025-2028 - Main investigator of grant project granted by Grant Agency of Czech Republic [POSTDOC INDIVIDUAL FELLOWSHIP OUTGOING](https://gacr.cz/pif-out-2026/): Long-term spatiotemporal dynamics in a plant-pollinator community and consequences for pollen transfer in a changing world (25-17193O)

## Educational stays abroad

-   2019 - 6-months Erasmus study abroad at University of Tartu (Estonia)

-   2022 - 2-months internship at Rey Juan Carlos University under supervision of Marcos Méndez

-   2023 - 1-month internship at University of Granada under supervision of Roccio Peréz Barrales

## Post-doctoral stays abroad

-   2025 - 2027 - 2 year stay abroad at [CREAF](https://www.creaf.cat/en) under supervision of Jordi Bosch within the [POSTDOC INDIVIDUAL FELLOWSHIP OUTGOING](https://gacr.cz/pif-out-2026/) project

## Conferences

-   2018 - SCAPE, The Scandinavian Association for Pollination Ecologists, Blessington, IRL (poster)

-   2019 - Kostelecké inspirování, CZU, CZE (oral presentation)

-   2019 - SCAPE, The Scandinavian Association for Pollination Ecologists, Höör, SWE (oral presentation)

-   2020 - EcoFlor conference, Bilbao, ESP (oral presentation)

-   2021 - EcoFlor online conference, Madrid ESP (organization and moderation of online discussion)

-   2022 - EcoFlor conference, Maó, ESP (oral presentation)

-   2022 - SCAPE, The Scandinavian Association for Pollination Ecologists, Warsaw, POL (oral presentation)

-   2023 - EcoFlor conference, Sevilla, ESP (oral presentation)

-   2024 - EcoFlor conference, Coimbra, POR (oral presentation)

-   2025 - EcoFlor conference, León, ESP (oral presentation)

## Teaching experience

-   R for life, Charles University in Prague, Czechia (2021, 2022; under leading of Martin Weiser and Tomáš Herben)

-   Practical course on Plant Morphology, Charles University in Prague, Czechia (2020; under leading of Martin Čertner)

-   Field course on Botany, Charles University in Prague, Czechia (2021; under leading of Jan Šťastný)

-   Field course on Phytocenological and Plant-population Methods, Charles University in Prague, Czechia (2021; under leading of Tomáš Koubek)

## Supervised students

-   Alice Haveldová (Bachelors, supervision, finished)

-   Karolína Chvojková (Bachelors, supervision, finished)

-   Natálie Hanusová (Bachelors and Masters, supervision, finished)

-   Klára Doksanská (Bachelors, supervision, ongoing)

-   Kateřina Příbramská (Bachelors, supervision, ongoing)

-   Aneta Hynčicová (Bachelors, supervision, ongoing)

-   Petr Švanda (Bachelors and Masters, supervision, ongoing)

-   Eva Matoušková (PhD, supervision, ongoning)

-   Zuzana Matějková (Bachelor and Masters, co-supervision, ongoing)

-   Lucie Holzbachová (Masters, co-supervision, ongoing)

## Field experience

-   2016-2017 - field work with Insect communities' group (main researcher Robert Tropek)

-   2018-2020 - field work experiments with Klará Koupilová and her project focused on plant pathogens transmitted by pollinators

-   2017-2023 - field work for master and PhD thesis in Czech Republic

-   2023 - 4 months of fieldwork in Andes, Ecuador

## Languages and skills

-   Czech (native)

-   English (fluent)

-   Spanish (advanced beginner)

-   driving license A1 and B

## Science popularization

-   2018 - 2020 - Guide in Botanical Garden of Faculty of Science, Charles University

-   2018 - 2024 - Co-author of tasks for biological competition Biozvěst

-   2019 - Co-author of exhibition "Intimní život rostlin" (The Intimate Life of Plants) in Botanical Garden of Prague (with Doc. RNDr. Lubomír Hrouda, CSc., RNDr. Zdeněk Janovský, Ph.D, RNDr. Jan Ponert PhD. and Mgr. Ludmila Němcová).

-   2020 - Co-author of popular science article about anther smuts (Živa)

-   2024 - now: Co-author of popularization Podcast "Opylovači"

## Publications

-   **Štenc**, J., Janošík, L., Freudenfeld, M., Matoušková, E., Hadrava, J., Mikát, M., ... & Janovský, Z. (2025). Pollen presentation mitigates competition for pollinators due to diurnal stratification of pollen transfer. *Perspectives in Plant Ecology, Evolution and Systematics*, *67*, 125868. <https://doi.org/10.1016/j.ppees.2025.125868>

-   Novotná Jaroměřská, T., Havránek, V., Novotný, D., Zawierucha, K., Romanenko, O., **Štenc**, J., ... & Trubač, J. (2025). Chasing (macro) elements in microinvertebrates: A new methodological approach for quantitative and qualitative analyses of phosphorus by PIXE (Particle‐Induced X‐Ray Emission) applied to glacier tardigrades. *Methods in Ecology and Evolution*, *16*(6), 1160-1172. <https://doi.org/10.1111/2041-210X.70023>

-   Janovský, Z., & **Štenc**, J. (2023). Pollinator community and generalisation of pollinator spectra changes with plant niche width and local dominance. *Functional Ecology*, 00, 1--10. <https://doi.org/10.1111/1365-2435.14439>

-   Matoušková, E., **Štenc**, J., & Janovský, Z. (2023). Innate preferences of *Eristalis tenax* L. (Syrphidae) for flower colour, size and symmetry are more intricate than the simple additive model. *Biological Journal of the Linnean Society*, 140(1), 110--119. <https://doi.org/10.1093/BIOLINNEAN/BLAD035>

-   **Štenc**, J., Janošík, L., Matoušková, E., Hadrava, J., Mikát, M., & Janovský, Z. (2023). Pollinator visitation closely tracks diurnal patterns in pollen release. *American Journal of Botany*, e16179. <https://doi.org/10.1002/AJB2.16179>

-   Koupilová, K., **Štenc**, J., & Janovský, Z. (2022). Pollinators adjust their behavior to presence of pollinator-transmitted pathogen in plant population. *Behavioral Ecology*, 33(2), 319--328. <https://doi.org/10.1093/BEHECO/ARAB153>

-   Koupilová, K., **Štenc**, J., & Janovský, Z. (2021). Pollen dispersal is driven by pollinator response to plant disease and plant spatial aggregation. *Basic and Applied Ecology*, 50, 77--86. <https://doi.org/10.1016/j.baae.2020.10.0072016-2017>

</div>
